server:
  port: 80

spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev

  #### jpa
  jpa:
    hibernate:
      ddl-auto: update #create X
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true

  #### datasource
  datasource:
    # url: jdbc:h2:tcp://localhost/~/develop/h2/commerce
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver

  #### h2
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

